In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
iris = datasets.load_iris()
X = iris.data 
y = iris.target 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 100.00%


In [2]:

import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
iris = datasets.load_iris()
X = iris.data 
y = iris.target 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()

nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
cm=confusion_matrix(y_test,y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
print(cm)

Accuracy: 100.00%
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [4]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of Naive Bayes: {accuracy:.2f}")
print("\nEnter the flower measurements:")
sepal_length = float(input("Sepal length (cm): "))
sepal_width = float(input("Sepal width (cm): "))
petal_length = float(input("Petal length (cm): "))
petal_width = float(input("Petal width (cm): "))
newrow = np.array([[sepal_length,sepal_width,petal_length,petal_width]])
prediction = nb_classifier.predict(newrow)
species = data.target_names[prediction[0]]
print(f"\nPredicted Iris species: {species}")


Accuracy of Naive Bayes: 1.00

Enter the flower measurements:
Sepal length (cm): 5.1
Sepal width (cm): 3.5
Petal length (cm): 1.4
Petal width (cm): 0.2

Predicted Iris species: setosa


In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

df = pd.read_csv("fruit.csv")
print(df.head())

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

y_pred = nb_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of Naive Bayes: {accuracy:.2f}")

print("\nEnter the fruit measurements:")

Weight = float(input("Enter the weight: "))
Size = float(input("Enter size: "))
Sweetness = float(input("Enter Sweetness: "))

newrow = np.array([[Weight, Size, Sweetness]])

prediction = nb_classifier.predict(newrow)

print(f"\nPredicted Fruit name: {prediction[0]}")


   Weight  Size  Sweetness  Fruit
0     145   6.8        7.8  Apple
1     150   7.0        8.0  Apple
2     155   7.1        7.6  Apple
3     160   7.2        7.9  Apple
4     148   6.9        8.2  Apple
Accuracy of Naive Bayes: 1.00

Enter the fruit measurements:
Enter the weight: 145
Enter size: 6.8
Enter Sweetness: 7.8

Predicted Fruit name: Apple
