In [3]:
# matrix operation(using vectorization)and transformation using python and svd using python
# usin numpy
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a+b
d=a-b
e=a*b
f=np.dot(a,b)
A_transpose=a.T
print("addition:")
print(c)
print("\nsubtraction:")
print(d)
print(" \nelement wise mulitiplication:")
print(e)
print("\nmatrix wise multiplication:")
print(f)
print("\ntranspose:")
print(A_transpose)

addition:
[[ 6  8]
 [10 12]]

subtraction:
[[-4 -4]
 [-4 -4]]
 
element wise mulitiplication:
[[ 5 12]
 [21 32]]

matrix wise multiplication:
[[19 22]
 [43 50]]

transpose:
[[1 3]
 [2 4]]


In [5]:
#with svd
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(X)
n_components=2
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("orginal  matrix:")
print(X)
print("\nReconstructed Matrix(with reduced dimensions):")
print(X_reconstructed)

orginal  matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
